# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_text', models.TextField()),
                ('boog_head', models.CharField(max_length=100)),
            ],
        ),
    ]
