# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogcontent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_content',
            old_name='boog_head',
            new_name='blog_head',
        ),
    ]
