# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcontent', '0003_auto_20160829_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('classify', models.CharField(default='other', max_length=200)),
                ('created_time', models.DateField()),
                ('content', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('tips', models.CharField(max_length=500)),
                ('reading_num', models.IntegerField()),
            ],
        ),
    ]
